id-rails-console triggers Slack notification (#24)

diff --git a/identity_base_config/files/default/id-rails-console b/identity_base_config/files/default/id-rails-console
--- a/identity_base_config/files/default/id-rails-console
+++ b/identity_base_config/files/default/id-rails-console
@@ -3,6 +3,7 @@ set -eu
 
 app=idp
 APP_USER="${APP_USER-websrv}"
+missing_keys=0
 
 ENV_VARS=("app=$app")
 
@@ -19,12 +20,15 @@ usage() {
     cat >&2 <<EOM
 usage: $(basename "$0") [APP]
 
-Run a rails console for APP (default "idp").
+Run a Rails console for APP (default "idp"). 
+
 This involves using sudo to change to the app service user, default $APP_USER.
-(Override by setting APP_USER).
+(Override by setting APP_USER). You will be prompted to provide a justification
+for creating this console, which will be recorded in the <%= @channel %>
+channel in Slack.
 
 If the env variable ALLOW_CONSOLE_DB_WRITE_ACCESS is set, it will be passed
-through to the rails console.
+through to the Rails console.
 EOM
 }
 
@@ -39,6 +43,25 @@ if [ $# -ge 1 ]; then
             ;;
     esac
 fi
+
+while true; do
+    read -r -p "Please provide an explanation for this Rails console: " USE_CASE
+    if [ ! -z "$USE_CASE" ]; then
+        break
+    fi
+done
+USE_CASE=$(echo $USE_CASE | sed 's/"/\\\"/g;s/\&/\&amp\;/g;s/</\&lt\;/g;s/>/\&gt\;/g')
+
+CHANNEL=$(cat /etc/login.gov/keys/slackchannel) || ((missing_keys++))
+WEBHOOK=$(cat /etc/login.gov/keys/slackwebhook) || ((missing_keys++))
+if [ ${missing_keys} -gt 0 ]; then
+    echo 'Slack channel/webhook missing! Verify files and run Chef to repopulate.'
+    exit 1
+fi
+
+TEXT=':rails: _rails console_ :rails: for `'"$(logname)"'` on `'"$(hostname)"'` :\n*'"${USE_CASE}"'*'
+PAYLOAD='payload={"channel": "'"${CHANNEL}"'", "username": "id-rails-console", "text": "'"${TEXT}"'", "icon_emoji": ":dopetopus:"}'
+curl -X POST --data-urlencode "${PAYLOAD}" $WEBHOOK
 
 set -x
 
