putting values in files / reverting back to file

diff --git a/identity_base_config/files/default/id-rails-console b/identity_base_config/files/default/id-rails-console
--- a/identity_base_config/files/default/id-rails-console
+++ b/identity_base_config/files/default/id-rails-console
@@ -3,6 +3,7 @@ set -eu
 
 app=idp
 APP_USER="${APP_USER-websrv}"
+missing_keys=0
 
 ENV_VARS=("app=$app")
 
@@ -50,13 +51,17 @@ while true; do
     fi
 done
 
-CURL='curl -X POST --data-urlencode '
+CHANNEL=$(cat /etc/login.gov/keys/slackchannel) || ((missing_keys++))
+WEBHOOK=$(cat /etc/login.gov/keys/slackwebhook) || ((missing_keys++))
+if [ ${missing_keys} -gt 0 ]; then
+    echo 'Slack channel/webhook missing! Verify files and run Chef to repopulate.'
+    exit 1
+fi
+
 TEXT=":rails:*rails console*:rails: for \`$(logname)\` on \`$(hostname)\`\nuse case: \\\"${USE_CASE}\\\""
-PAYLOAD="'payload={\"channel\": \"<%= @channel %>\", \"username\": \"id-rails-console\", \"text\": \"${TEXT}\", \"icon_emoji\": \":dopetopus:\"}'"
-bash -c "${CURL} ${PAYLOAD} <%= @webhook %>"
+PAYLOAD="'payload={\"channel\": \"${CHANNEL}\", \"username\": \"id-rails-console\", \"text\": \"${TEXT}\", \"icon_emoji\": \":dopetopus:\"}'"
+curl -X POST --data-urlencode "${PAYLOAD} ${WEBHOOK}"
 
 set -x
 
 exec sudo -H -u "$APP_USER" env "${ENV_VARS[@]}" sh -euxc "cd '/srv/$app/current'; bundle exec rails c"
-
-
